### ISSUE TITLE
determineFallback requires last URLSegment to not exist in SiteTree

### ISSUE THREAD

**Issue by SilbinaryWolf** [nglasl/silverstripe-misdirection#15]
In relation to:
https://github.com/nglasl/silverstripe-misdirection/pull/14

MisdirectionService->determineFallback requires last URLSegment to not exist in SiteTree for the function to actually work. This doesn't play too nicely if someone manually throws a httpError.

As changing this behaviour could result in something unexpected, I'm leaving this issue here for discussion in the future.

**Comment by nglasl** [comment]
https://github.com/nglasl/silverstripe-misdirection/issues/16
