### ISSUE TITLE
Problems with Fluent

### ISSUE THREAD

**Issue by francesko** [nglasl/silverstripe-misdirection#18]
We are having trouble using this module with Fluent (https://github.com/tractorcow/silverstripe-fluent).
If we try to add a link mapping starting with a locale (e.g. en/example/page.html), the redirection doesn't occur properly and a 404 is returned.

We commented some lines in MisdirectionRequestFilter to make it work properly:
https://github.com/unibz/silverstripe-misdirection/commit/a06a811ed31a53c96d0088fc47cc7f581ec4c7d0

Is there any reason why you are doing the rules check?

In the comments it says:

> Bypass the request filter when requesting specific director rules such as "/admin" or "/dev".

but even by commenting those lines of code those routes work just fine.

Do you have any other suggestions on how to fix this?

**Comment by nglasl** [comment]
This was originally built with the intention to prevent users from creating link mappings for things such as **/admin**, therefore preventing access to the back end. I've now pushed something up to master which will only bypass specific rules, therefore the fluent director rules should now work as expected. I will create a new release soon.
