### ISSUE TITLE
consider capital letters in URL

### ISSUE THREAD

**Issue by leonixyz** [nglasl/silverstripe-misdirection#19]
Hello,
if I try to insert a URL having capital letters (i.e. **www.hello.com?key=VALUE**) the module rewrites them lowecase. Is this desires behaviour? is it possible to change it?
thanks
Giulio

**Comment by nglasl** [comment]
Hi Giulio,

This was a design decision, aiming to provide consistency when matching URLs. There may be consideration further down the track for passing GET parameters through, in which case maintaining their case might make more sense.

Kind Regards,

Nathan

**Comment by leonixyz** [comment]
Thank you Nathan,
I worked around this by url-encoding capital letters in the GET parameters
http://www.degraeve.com/reference/urlencoding.php

It'd be nice to carry on this consideration for the next versions of Misdirection.

Regards
Giulio

**Comment by nglasl** [comment]
I'm glad you managed to work around this for now, but yes, it is definitely a consideration for a future version :)
