### ISSUE TITLE
Regex LinkMappings not matching on GET parameters

### ISSUE THREAD

**Issue by leonixyz** [nglasl/silverstripe-misdirection#21]
Dear Nathan,

I was wondering why you choosed to deal in this specific way with regex LinkMappings:

if the requested URL is http://example.org/mystring?p=1 the module matches the regex only against the base URL, discarding the GET parameters: http://example.org/mystring (code/services/MisdirectionService.php:98)

~~~
if((!$match->IncludesHostname && preg_match("%{$match->MappedLink}%", $base)) || ($match->IncludesHostname && preg_match("%{$match->MappedLink}%", "{$host}/{$base}"))) {
    $filtered->push($match);
}
~~~

moreover, you explicitly set the matched URL to the base URL (code/services/MisdirectionService.php:143)

~~~
$match->setMatchedURL($match->IncludesHostname ? "{$host}/{$base}" : $base);
return $match;
~~~

can you please explain why do you do that?
This prevents having regex matching GET parameters, for example:
`\?parameter=([0-9]+)` --> `http://exaple.org/$1/something`

Thank you
Giulio

**Comment by nglasl** [comment]
This would have been an oversight during early development. Perhaps it didn't meet a requirement at the time. I have corrected this on the latest commit to master, and GET parameters can now be matched against. Thanks!
