### ISSUE TITLE
Admin tab does not show on subsites

### ISSUE THREAD

**Issue by 3Dgoo** [nglasl/silverstripe-misdirection#23]
When Misdirection is used with the SilverStripe Subsites module the Misdirection admin panel does not display when viewing sub sites. This is because the Subsites module requires the following code in the ModelAdmin class:

	public function subsiteCMSShowInMenu() {
		return true;
	}

Are you happy with me adding this in so the module displays correctly when using the Subsites module?

**Comment by nglasl** [comment]
Thanks for getting in touch. To me, it seems like that should be added using an extension from your project. It basically seems like a means of saying "make sure you actually want to use this between sites", in which case, forcing it to be true from the module doesn't make a lot of sense.

**Comment by 3Dgoo** [comment]
Thanks Nathan. I'll give that a try and see if that works.
