### ISSUE TITLE
SS4 compatability

### ISSUE THREAD

**Issue by guyvanbael** [nglasl/silverstripe-misdirection#26]
Any plans for a SS4 compatible version?

**Comment by nglasl** [comment]
Definitely. I will be going through and doing SS4 upgrades across my modules in the near future. I've added a project over at the following to highlight this :)

https://github.com/nglasl/silverstripe-misdirection/projects

**Comment by guyvanbael** [comment]
Hi, is there any news on the SS4 compatibilty. I have a project coming up (ss4) and would like to use this module.
Thanks,
Guy

**Comment by nglasl** [comment]
Thanks for getting in touch!

I've recently updated two of my modules to SS4, however this one has fallen behind in terms of priority. It's definitely still on the list, however it may still be another month or two away at the soonest. If you absolutely need some redirects in place for your project right now, I suggest looking at using `.htaccess` rules until this is ready to go. Alternatively, you're more than welcome to make a PR.

**Comment by nglasl** [comment]
@guyvanbael, just letting you know that the module now supports SS4. Thanks for your patience :)
