### ISSUE TITLE
Link mapping permissions

### ISSUE THREAD

**Issue by tardinha** [nglasl/silverstripe-misdirection#33]
Hey,

Just wondering if LinkMapping needs to have canView, canEdit, canCreate and canDelete applied to it, as it extends DataObject, it will inherit these anyway?

By default, DataObjects require admin access to edit them, which leaves content authors unable to work with quite a lot of content on most sites (even adding userform radio options is a no go!).

To overcome this, I created an extension which allows admins to configure groups to be able to edit any DataObjects which have the extension applied. However, this doesn't work on LinkMapping.

Any thoughts?

Cheers

Mark

**Comment by nglasl** [comment]
Hey @tardinha, this is a general thing that I've done with all data objects on my modules, and that's because the default permissions for data objects aren't great when you consider content authors. In this case, I wanted to be very explicit about only admins changing link mappings (for obvious reasons). But I agree, this can be done a little better so you can at least extend the permissions with your own.

**Comment by tardinha** [comment]
Yep, agreed on admin only, but we have some people we can trust with redirects, but not other admin tasks ;)

Cheers

Mark

**Comment by wilr** [comment]
@tardinha @nglasl implemented permission check so that if non-admin has access to the Misdirection admin then they can edit / delete (https://github.com/nglasl/silverstripe-misdirection/pull/35/files)

**Comment by sparkcom** [comment]
@nglasl wonder if  wilr's update can be merged into your next lease? It's much more flexible to allow admin to assign this to a group of people, for example, SEO agency, who needs to sort out some 404 when a new website is launched.

**Comment by nglasl** [comment]
Ah yes, thanks for the reminder @sparkcom and for the PR @wilr. I need to sort a few things out soon, so I'll look at getting all active PRs in at the same time. Will keep you posted.

**Comment by nglasl** [comment]
Just a heads up this has now been merged into https://github.com/symbiote/silverstripe-misdirection, which will now be the source of truth for packagist moving forward. Appreciate all the hard work here!
